param(
    [switch]$Check,
    [switch]$ValidateOnly,
    [ValidateSet("All", "Cpp", "TileIds", "Js")]
    [string]$Target = "All",
    [string]$TileIdsPath = "",
    [string]$TilePalettePath = "",
    [string]$JsPath = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptDir "..")
$sourcePath = Join-Path $repoRoot "Assets\Palette\TilePalette.json"

if ([string]::IsNullOrWhiteSpace($TileIdsPath)) {
    $TileIdsPath = Join-Path $repoRoot "src\Core\World\TileIdsGenerated.h"
}

if ([string]::IsNullOrWhiteSpace($TilePalettePath)) {
    $TilePalettePath = Join-Path $repoRoot "src\Core\Presentation\TilePaletteGenerated.h"
}

if ([string]::IsNullOrWhiteSpace($JsPath)) {
    $JsPath = Join-Path $repoRoot "FusouMapForge\generated\tile-palette.generated.js"
}

$targetTileIdsPath = $TileIdsPath
$targetTilePalettePath = $TilePalettePath
$targetJsPath = $JsPath

function Read-TilePaletteSource {
    if (-not (Test-Path -LiteralPath $sourcePath)) {
        throw "Palette source not found: $sourcePath"
    }

    return Get-Content -Raw -Encoding UTF8 -LiteralPath $sourcePath | ConvertFrom-Json
}

function Assert-IntRange {
    param(
        [string]$Name,
        [object]$Value,
        [int]$Min,
        [int]$Max
    )

    if ($Value -isnot [int] -and $Value -isnot [long]) {
        throw "$Name must be an integer."
    }

    if ($Value -lt $Min -or $Value -gt $Max) {
        throw "$Name must be in range $Min..$Max."
    }
}

function Test-PascalName {
    param([string]$Name)

    return $Name -cmatch "^[A-Z][A-Za-z0-9]*$"
}

function Test-CppConstantName {
    param([string]$Name)

    return $Name -cmatch "^k[A-Z][A-Za-z0-9]*$"
}

function Assert-TilePaletteSource {
    param([object]$Palette)

    Assert-IntRange "version" $Palette.version 1 1
    Assert-IntRange "maxTileId" $Palette.maxTileId 0 255

    if ($null -eq $Palette.consoleColors -or $Palette.consoleColors.Count -ne 16) {
        throw "consoleColors must contain exactly 16 entries."
    }

    $seenColorIds = @{}
    foreach ($color in $Palette.consoleColors) {
        Assert-IntRange "consoleColors.id" $color.id 0 15
        if ($seenColorIds.ContainsKey($color.id)) {
            throw "Duplicate console color id: $($color.id)"
        }
        $seenColorIds[$color.id] = $true

        if (-not (Test-PascalName $color.cppName)) {
            throw "Invalid console color cppName: $($color.cppName)"
        }
        if ([string]::IsNullOrWhiteSpace($color.name)) {
            throw "Console color name must not be empty. id=$($color.id)"
        }
        if ($color.hex -cnotmatch "^#[0-9A-Fa-f]{6}$") {
            throw "Invalid console color hex: $($color.hex)"
        }
    }

    if ($null -eq $Palette.tiles -or $Palette.tiles.Count -eq 0) {
        throw "tiles must not be empty."
    }

    $seenTileIds = @{}
    foreach ($tile in $Palette.tiles) {
        Assert-IntRange "tiles.id" $tile.id 0 $Palette.maxTileId
        if ($seenTileIds.ContainsKey($tile.id)) {
            throw "Duplicate tile id: $($tile.id)"
        }
        $seenTileIds[$tile.id] = $true

        if (-not (Test-CppConstantName $tile.cppName)) {
            throw "Invalid tile cppName: $($tile.cppName)"
        }
        if ([string]::IsNullOrWhiteSpace($tile.name)) {
            throw "Tile name must not be empty. id=$($tile.id)"
        }
        if ($null -eq $tile.glyph -or [string]$tile.glyph -eq "") {
            throw "Tile glyph must not be empty. id=$($tile.id)"
        }
        Assert-IntRange "tiles.defaultFg" $tile.defaultFg 0 15
        Assert-IntRange "tiles.defaultBg" $tile.defaultBg 0 15
    }
}

function ConvertTo-CppGlyphLiteral {
    param([string]$Glyph)

    if ($Glyph.Length -eq 1) {
        $codePoint = [int][char]$Glyph[0]
        return ("U'\U{0:X8}'" -f $codePoint)
    }

    if ($Glyph.Length -eq 2 -and [char]::IsSurrogatePair($Glyph, 0)) {
        $codePoint = [char]::ConvertToUtf32($Glyph, 0)
        return ("U'\U{0:X8}'" -f $codePoint)
    }

    throw "C++ glyph must contain exactly one Unicode scalar value: $Glyph"
}

function ConvertTo-JsStringLiteral {
    param([string]$Value)

    return ($Value | ConvertTo-Json -Compress)
}

function New-TileIdsHeader {
    param([object]$Palette)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("// Copyright (c) 2026 Bruce Yan. All Rights Reserved.")
    $lines.Add("// This file is generated by tools/GenerateTilePalette.ps1. Do not edit manually.")
    $lines.Add("")
    $lines.Add("#pragma once")
    $lines.Add("")
    $lines.Add("#include <cstdint>")
    $lines.Add("")
    $lines.Add("namespace core")
    $lines.Add("{")
    $lines.Add("    namespace world")
    $lines.Add("    {")
    $lines.Add("        using TileId = std::uint8_t;")
    $lines.Add("")
    $lines.Add(("        inline constexpr TileId kGeneratedMaxTileId = {0};" -f $Palette.maxTileId))
    $lines.Add("")
    $lines.Add("        namespace tileid")
    $lines.Add("        {")
    foreach ($tile in ($Palette.tiles | Sort-Object id)) {
        $lines.Add(("            inline constexpr TileId {0} = {1};" -f $tile.cppName, $tile.id))
    }
    $lines.Add("        } // namespace tileid")
    $lines.Add("    } // namespace world")
    $lines.Add("} // namespace core")
    $lines.Add("")

    return ($lines -join "`r`n")
}

function New-TilePaletteHeader {
    param([object]$Palette)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("// Copyright (c) 2026 Bruce Yan. All Rights Reserved.")
    $lines.Add("// This file is generated by tools/GenerateTilePalette.ps1. Do not edit manually.")
    $lines.Add("")
    $lines.Add("#pragma once")
    $lines.Add("")
    $lines.Add("#include ""src/Core/Render/CellBuffer.h""")
    $lines.Add("#include ""src/Core/World/TileMap.h""")
    $lines.Add("")
    $lines.Add("#include <array>")
    $lines.Add("#include <cstddef>")
    $lines.Add("")
    $lines.Add("namespace core")
    $lines.Add("{")
    $lines.Add("    namespace presentation")
    $lines.Add("    {")
    $lines.Add("        using GeneratedCellPaletteArray = std::array<core::render::Cell, static_cast<std::size_t>(core::world::kGeneratedMaxTileId + 1)>;")
    $lines.Add("")
    $lines.Add("        [[nodiscard]] inline GeneratedCellPaletteArray makeGeneratedTilePalette() noexcept")
    $lines.Add("        {")
    $lines.Add("            GeneratedCellPaletteArray palette{};")
    $lines.Add("")
    foreach ($tile in ($Palette.tiles | Sort-Object id)) {
        $glyphLiteral = ConvertTo-CppGlyphLiteral ([string]$tile.glyph)
        $lines.Add(("            palette[core::world::tileid::{0}].glyph_ = {1};" -f $tile.cppName, $glyphLiteral))
    }
    $lines.Add("")
    $lines.Add("            return palette;")
    $lines.Add("        }")
    $lines.Add("    } // namespace presentation")
    $lines.Add("} // namespace core")
    $lines.Add("")

    return ($lines -join "`r`n")
}

function New-TilePaletteJs {
    param([object]$Palette)

    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add("// This file is generated by tools/GenerateTilePalette.ps1. Do not edit manually.")
    $lines.Add("(function (global) {")
    $lines.Add("  'use strict';")
    $lines.Add("")
    $lines.Add("  const CONSOLE16 = {")
    $lines.Add("    NAMES: [")
    foreach ($color in ($Palette.consoleColors | Sort-Object id)) {
        $lines.Add(("      {0}," -f (ConvertTo-JsStringLiteral ([string]$color.name))))
    }
    $lines.Add("    ],")
    $lines.Add("    HEX: [")
    foreach ($color in ($Palette.consoleColors | Sort-Object id)) {
        $lines.Add(("      {0}," -f (ConvertTo-JsStringLiteral ([string]$color.hex))))
    }
    $lines.Add("    ],")
    $lines.Add("    DEFAULT_FG: 0,")
    $lines.Add("    DEFAULT_BG: 15")
    $lines.Add("  };")
    $lines.Add("")
    $lines.Add("  const DEFAULT_PALETTE_CONFIG = {")
    $lines.Add("    version: 1,")
    $lines.Add("    entries: [")
    foreach ($tile in $Palette.tiles) {
        $lines.Add(("      {{ id: {0}, glyph: {1}, name: {2} }}," -f $tile.id, (ConvertTo-JsStringLiteral ([string]$tile.glyph)), (ConvertTo-JsStringLiteral ([string]$tile.name))))
    }
    $lines.Add("    ]")
    $lines.Add("  };")
    $lines.Add("")
    $lines.Add("  const DEFAULT_BRUSH_COLORS = {")
    foreach ($tile in $Palette.tiles) {
        $lines.Add(("    {0}: {{ fg: {1}, bg: {2} }}," -f $tile.id, $tile.defaultFg, $tile.defaultBg))
    }
    $lines.Add("  };")
    $lines.Add("")
    $lines.Add("  global.appGeneratedTilePalette = {")
    $lines.Add(("    version: {0}," -f $Palette.version))
    $lines.Add(("    maxTileId: {0}," -f $Palette.maxTileId))
    $lines.Add("    CONSOLE16,")
    $lines.Add("    DEFAULT_PALETTE_CONFIG,")
    $lines.Add("    DEFAULT_BRUSH_COLORS")
    $lines.Add("  };")
    $lines.Add("")
    $lines.Add("  global.appConstAsset = global.appConstAsset || {};")
    $lines.Add("  global.appConstAsset.CONSOLE16 = CONSOLE16;")
    $lines.Add("")
    $lines.Add("  global.appDefaults = global.appDefaults || {};")
    $lines.Add("  global.appDefaults.DEFAULT_PALETTE_CONFIG = DEFAULT_PALETTE_CONFIG;")
    $lines.Add("  global.appDefaults.DEFAULT_BRUSH_COLORS = DEFAULT_BRUSH_COLORS;")
    $lines.Add("})(window);")
    $lines.Add("")

    return ($lines -join "`r`n")
}

function Compare-OrWriteFile {
    param(
        [string]$Path,
        [string]$Content
    )

    if ($Check) {
        if (-not (Test-Path -LiteralPath $Path)) {
            throw "Generated file is missing: $Path"
        }

        $existing = Get-Content -Raw -Encoding UTF8 -LiteralPath $Path
        if ($existing -ne $Content) {
            throw "Generated file is out of date: $Path"
        }
        return
    }

    $parent = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Path $parent | Out-Null
    }

    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

$palette = Read-TilePaletteSource
Assert-TilePaletteSource $palette

if ($ValidateOnly) {
    Write-Host "Palette source is valid: $sourcePath"
    exit 0
}

if ($Target -eq "All" -or $Target -eq "Cpp" -or $Target -eq "TileIds") {
    $tileIdsHeader = New-TileIdsHeader $palette

    Compare-OrWriteFile $targetTileIdsPath $tileIdsHeader
}

if ($Target -eq "All" -or $Target -eq "Cpp") {
    $tilePaletteHeader = New-TilePaletteHeader $palette

    Compare-OrWriteFile $targetTilePalettePath $tilePaletteHeader
}

if ($Target -eq "All" -or $Target -eq "Js") {
    $tilePaletteJs = New-TilePaletteJs $palette

    Compare-OrWriteFile $targetJsPath $tilePaletteJs
}

if ($Check) {
    Write-Host "Generated tile palette files are up to date. Target: $Target"
}
else {
    Write-Host "Generated tile palette files were written. Target: $Target"
}
